[package]
name = "passgen"
version = "0.2.0"
authors = ["Patrick Barrett <patrick@mkii.org>"]
description = "An incrdibly simple command line password generator."
repository = "https://github.com/azdle/passgen"
readme = "README.md"
license = "Apache-2.0"

[dependencies]
clap = "2"
rand = "0.3"